// <auto-generated />
using LoanManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanManagement.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20221221125040_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoanManagement.Model.LoanType", b =>
                {
                    b.Property<string>("LoanName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoanDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanImagepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanName");

                    b.ToTable("LoanTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
